### ISSUE TITLE
Issue with dict.iteritems

### ISSUE THREAD

**Issue by lcorbel** [dennybritz/chatbot-retrieval#22]
Ok so this one is in between your code and tensorflow potentially being bugged. I'm just posting my quick fix for other people to see.

So if you get the "AttributeError: 'dict' object has no attribute 'iteritems' " error when running udc_train.py, the simple fix is to change all occurences of 'iteritems' in graph_io.py by 'items' (using sed for example).

I know it is not a good long term solution but it will allow you to run the script at least temporally.

**Comment by amirj** [comment]
As you are in python3 , use dict.items() instead of dict.iteritems()

iteritems() was removed in python3, so you can't use this method anymore.

Take a look at Python Wiki (Link)

In Built-in Changes part, it is stated that

Removed dict.iteritems(), dict.iterkeys(), and dict.itervalues().

Instead: use dict.items(), dict.keys(), and dict.values() respectively.

Amir H. Jadidinejad

**Comment by Sangheli** [comment]
fixed in tensorflow 0.11 and above

**Comment by dennybritz** [comment]
Closing this :)
