### ISSUE TITLE
How predict all responses at one time?

### ISSUE THREAD

**Issue by Sangheli** [dennybritz/chatbot-retrieval#31]
in [udc_predict.py at line 57](https://github.com/dennybritz/chatbot-retrieval/blob/master/udc_predict.py#L57), the answer is predict step by step, this will cause creating new gpu device every time
this will take some time( 1 sec or above).

how predict all responses as array at one time?
in tensorflow readme [says](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard3/tf.contrib.learn.Estimator.md#tfcontriblearnestimatorpredictargs-kwargs-estimatorpredict )

```
Args:

**x**: Matrix of shape [n_samples, n_features...]. Can be iterator that returns arrays of features. The training input samples for fitting the model. If set, input_fn must be None.
```

**Comment by dennybritz** [comment]
Two options:

- You could try using the `X` and `y` arguments you mention above instead of the `input_fn`. Then you can make X an iterator of examples instead of just a single one.
- You could modify get_features to use a Queue and produce multiple examples.

**Comment by Sangheli** [comment]
Thank you, im my fork I have implemented a second option, similar to the test mode

https://github.com/Sangheli/chatbot-retrieval

**Comment by lefnire** [comment]
@Samurais thanks for posting your branch! I had the same question, very helpful.

**Comment by Monireh2** [comment]
@Sangheli In your prediction code (your udc_predict.py), it is true that you are sending all the potential responses to the estimator at once but the answer is always the first response in the potential responses simply because the estimator ignore other elements in the potential responses list. In fact, although you give the features extracted from whole potential responses into the estimator but based on my observations it always gives the first element in the potential_responses as an answer. However, if you put the estimator in the loop exactly like what it is in Denny's code, you will get the correct response but unfortunately, it takes very long time to get the response for 500 potential responses....

**Comment by e-budur** [comment]
My observation is that the model tends to predict 100% for all candidates hence choose the first candidate as the answer. 

Therefore, the model doesn't actually perform well as much as the reported accuracy score.


Monireh2 <notifications@github.com> şunları yazdı (3 Ağu 2017 00:17):

**Comment by Monireh2** [comment]
@e-budur This is the case for Sangheli's version of prediction. It always takes the first response as the best one, but when I give the potential_responses one by one to the estimator as it is in Denny's original prediction code, it works correctly but it is as slow as the prediction takes 4 minutes for 500 potential responses!!!
